
import __ASTRO_IMAGE_IMPORT_ZEgcBq from "./images/beyond-survival.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fbeyond-survival.md";
import __ASTRO_IMAGE_IMPORT_fQt7x from "./images/i-hope-we-choose-love.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fi-hope-we-choose-love.md";
import __ASTRO_IMAGE_IMPORT_11Ss2w from "./images/fierce-intimacy.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffierce-intimacy.md";
import __ASTRO_IMAGE_IMPORT_1rFceL from "./images/educated.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Feducated.md";
import __ASTRO_IMAGE_IMPORT_Z1trz7D from "./images/nettle-and-bone.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fnettle-and-bone.md";
import __ASTRO_IMAGE_IMPORT_1u7RXj from "./images/emotionally-focused-family-therapy.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Femotionally-focused-family-therapy.md";
import __ASTRO_IMAGE_IMPORT_Z2fFrp2 from "./images/smitten.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fsmitten.md";
import __ASTRO_IMAGE_IMPORT_10hun3 from "./images/holy-shit.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fholy-shit.md";
import __ASTRO_IMAGE_IMPORT_CBoPU from "./images/the-great-shadow.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fthe-great-shadow.md";
import __ASTRO_IMAGE_IMPORT_Z8Kty6 from "./images/severence.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fseverance.md";
import __ASTRO_IMAGE_IMPORT_Zj3vxF from "./images/transforming-adhd.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ftransforming-adhd.md";
import __ASTRO_IMAGE_IMPORT_Z8cYSc from "./images/to-catch-a-fascist.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fto-catch-a-fascist.md";
import __ASTRO_IMAGE_IMPORT_Z1hY82k from "./images/was-that-racist.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwas-that-racist.md";
import __ASTRO_IMAGE_IMPORT_1LOgzF from "./images/undimmed.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fundimmed.md";
import __ASTRO_IMAGE_IMPORT_Z1kha7k from "./images/this-is-how-you-lose-the-time-war.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fthis-is-how-you-lose-the-time-war.md";
import __ASTRO_IMAGE_IMPORT_2h6D4a from "./images/when-trees-testify.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwhen-trees-testify.md";
export default new Map([["./images/beyond-survival.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fbeyond-survival.md", __ASTRO_IMAGE_IMPORT_ZEgcBq], ["./images/i-hope-we-choose-love.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fi-hope-we-choose-love.md", __ASTRO_IMAGE_IMPORT_fQt7x], ["./images/fierce-intimacy.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffierce-intimacy.md", __ASTRO_IMAGE_IMPORT_11Ss2w], ["./images/educated.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Feducated.md", __ASTRO_IMAGE_IMPORT_1rFceL], ["./images/nettle-and-bone.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fnettle-and-bone.md", __ASTRO_IMAGE_IMPORT_Z1trz7D], ["./images/emotionally-focused-family-therapy.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Femotionally-focused-family-therapy.md", __ASTRO_IMAGE_IMPORT_1u7RXj], ["./images/smitten.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fsmitten.md", __ASTRO_IMAGE_IMPORT_Z2fFrp2], ["./images/holy-shit.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fholy-shit.md", __ASTRO_IMAGE_IMPORT_10hun3], ["./images/the-great-shadow.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fthe-great-shadow.md", __ASTRO_IMAGE_IMPORT_CBoPU], ["./images/severence.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fseverance.md", __ASTRO_IMAGE_IMPORT_Z8Kty6], ["./images/transforming-adhd.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ftransforming-adhd.md", __ASTRO_IMAGE_IMPORT_Zj3vxF], ["./images/to-catch-a-fascist.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fto-catch-a-fascist.md", __ASTRO_IMAGE_IMPORT_Z8cYSc], ["./images/was-that-racist.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwas-that-racist.md", __ASTRO_IMAGE_IMPORT_Z1hY82k], ["./images/undimmed.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fundimmed.md", __ASTRO_IMAGE_IMPORT_1LOgzF], ["./images/this-is-how-you-lose-the-time-war.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fthis-is-how-you-lose-the-time-war.md", __ASTRO_IMAGE_IMPORT_Z1kha7k], ["./images/when-trees-testify.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwhen-trees-testify.md", __ASTRO_IMAGE_IMPORT_2h6D4a]]);
		